### PR TITLE
fix infinite loop after digging a stargate

### PR DESCRIPTION
**Pull request by HybridDog**

### CODE REVIEW

**Comment by sofar** [comment]
That's quite the cleanup. At what point is the actual fix? :)

**Comment by HybridDog** [comment]
> At what point is the actual fix? :)

The fix is done by removing that line:
https://github.com/minetest-mods/stargate/blob/master/gate_defs.lua#L148
removeGate is called before the gate becomes destructed and it calls itself by removing the node, which is not necessary and causes only an infinite loop

**Comment by sofar** [comment]
@HybridDog you have to stop making PR's with hundreds of lines of change, and then include a 1-liner bugfix as the "reason".

That's just really bad form.

Please submit 2 separate PR's. One with the one-liner fix, and a separate PR with the code cleanups.

**Comment by HybridDog** [comment]
> @HybridDog you have to stop making PR's with hundreds of lines of change, and then include a 1-liner bugfix as the "reason".
> 
> That's just really bad form.

l agree

> Please submit 2 separate PR's. One with the one-liner fix, and a separate PR with the code cleanups.

ok

**Pull request closed without merging**
